data:
  data_augmentation: 'baseline' # ['baseline', 'murat']
  input_size: 512
  binary: True
  num_classes: 2
  mean: [0.41326871514320374, 0.2723627984523773, 0.18590997159481049] # 512
  std:  [0.29345420002937317, 0.20033970475196838, 0.15474912524223328] # 512

model:
  network: resnet50 # [resnet50, bagnet33]
  pretrained: true # load weights from pre-trained model training on ImageNet
  checkpoint: null # load weights from other pretrained model

train:
  pin_memory: true # enables fast data transfer to CUDA-enabled GPUs
  num_workers: 2 # number of cpus used to load data at each step